### ISSUE TITLE
Generate the client with the OpenAPI spec

### ISSUE THREAD

**Issue by roidelapluie** [datadrivers/go-nexus-client#1]
Instead of rewriting the client, we should just generate it from the OpenAPI spec of Nexus.

**Comment by roidelapluie** [comment]
@Nosmoht what do you think?? it would make our lives easier

**Comment by Nosmoht** [comment]
Sounds great. Go ahead ;)

**Comment by anmoel** [comment]
it is not so simple possible.

The field "operationId" of the repository API endpoints is numbered in the swagger.json for nexus3.
All codegen tools generates function with a number instead of a repository type

**Comment by roidelapluie** [comment]
:(
