### ISSUE TITLE
Improve handling of different applicable action types in privilege/* resources 

### ISSUE THREAD

**Issue by fabrue** [datadrivers/go-nexus-client#119]
Each privilege resources has a different set of applicable actions. See [here](https://help.sonatype.com/repomanager3/nexus-repository-administration/access-control/privileges#Privileges-PrivilegeTypes) for reference. 

Improve handling of those resources. Perhaps by using enums/enum-like structures.

Resources were initially introduced in [this PR](https://github.com/datadrivers/go-nexus-client/pull/118)

**Comment by anmoel** [comment]
it is released in tag [1.7.0](https://github.com/datadrivers/go-nexus-client/releases/tag/1.7.0)
