### ISSUE TITLE
UserRead always fetch all users

### ISSUE THREAD

**Issue by marcelobartsch** [datadrivers/go-nexus-client#55]
In the function UserRead , even it accept a user id, it always fetch ALL users from nexus, which make no sense as the API support to filter directly.

https://github.com/datadrivers/go-nexus-client/blob/a796dd58024ce7e0787fc534560016c718ff802e/user.go#L53

service/rest/v1/security/users?userId=admin

PR Created #56

**Comment by anmoel** [comment]
merged in version v0.18.0
