### ISSUE TITLE
Azure Blob Storage support?

### ISSUE THREAD

**Issue by sonu27** [datadrivers/go-nexus-client#58]
Hi,

Will Azure Blob Storage support be added anytime soon?

From looking at the code it seems `BlobstoreS3BucketConfiguration` is using the JSON key `bucketConfiguration` which could cause problems with this. I'm happy to create a PR but need some guidance.

Ref: https://github.com/datadrivers/terraform-provider-nexus/issues/105

**Comment by anmoel** [comment]
implemented with release v1.0.0
